### ISSUE TITLE
It's possible to add @type array?

### ISSUE THREAD

**Issue by isaactopo** [HashandSalt/kirby3-schema#3]
Hi, 
it's probably a thing todo in @spatie builder but could be nice to specify multiple `@types` like @jayholtslander specifies [here](https://github.com/JayHoltslander/Structured-Data-JSON-LD/blob/master/LocalBusiness-2.json): 
```json
{
	"@context": "http://schema.org/",
	"@type": [
		"Organization",
		"LocalBusiness",
		"LegalService"
	],
```

Thanks!

**Comment by JayHoltslander** [comment]
@isaactopo Since authoring that bit I’ve learned that Organization is assumed when specifying LocalBusiness and LocalBusiness is assumed when specifying LegalService.
They’re more specific sub-types.
In my example all you’d really need is LegalService for Google to understand all three.

**Comment by isaactopo** [comment]
Thanks for your clarification on this @JayHoltslander, appreciated!
