### ISSUE TITLE
Call to undefined method Spatie\SchemaOrg\Schema::()

### ISSUE THREAD

**Issue by vasilisakarelova** [HashandSalt/kirby3-schema#4]
Hi! I am getting this error `Call to undefined method Spatie\SchemaOrg\Schema::()`, even though i do have Spatie installed in vendor folder, and it used to work. But them one day I open my website and get this error. What could cause the error? May be this plugin is not compatible with something?

**Comment by HashandSalt** [comment]
Dependencies have been upgraded. Works fine on Kirby 3.6.
