### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by muppet922** [HashandSalt/kirby3-schema#5]
Hello bro, can you make a little tutorial on wiki github page to help us implement it on our websites, thanks.

**Comment by HashandSalt** [comment]
It really depends what the schema is for. There are some good references here to get you started. You can essentially recreate those with this plugin.  [https://jsonld.com/](https://jsonld.com/).

For example, a video schema would look something like this:

```
<?= $site->schema('VideoObject')
->name('Funny Cat Poses 2.0')
->description("A short description of your video, we'd keep it at 140 characters just to be safe.")
->thumbnailUrl('http://www.example.com/thumbnail.jpg')
->uploadDate('2015-04-05T08:00:00+02:00')
->duration('PT1M33S')
->contentUrl('http://www.example.com/movie.mov')
->embedUrl('http://www.example.com/embed?videoetc')
?>
```

You can of course replace the data with field data.
